## **TensorFlow**

**TensorFlow** is an open-source machine learning framework developed by the Google Brain team. It's a versatile and powerful machine learning framework that is widely used in both research and industry. TensorFlow offers a rich ecosystem and a variety of tools to support the development, training, and deployment of machine learning models, particularly deep learning models. 

- **Tensor Computation**: It's designed to facilitate the development and deployment of machine learning and deep learning models. Tensor is a general name of multi-way array data. It's the standard way of representing data in TensorFlow. Tensors are multidimensional arrays, an extension of two-dimensional tables (matrices) yo data with higher dimension.

![image](https://tensorflownet.readthedocs.io/en/latest/_static/tensor-naming.png)

For example, 1d-tensor is a vector, 2d-tensor is a matrix and 3d-tensor is a cube. The 4d-tensor can be imaged as a vector of cubes. In a similar way, 5d-tensor is a matrix of cubes, and 6d-tensor is a cube of cubes.

![image](https://forum.huawei.com/enterprise/en/data/attachment/forum/202105/25/202703rdkpu52dhd2vgru6.png?%E6%88%AA%E5%9B%BE1.PNG)

In [11]:
import tensorflow as tf
import numpy as np

In [12]:
# check the current version of tf 
tf.__version__

'2.14.0'

### **Creating a Tensor:**

In [13]:
# Rank 0 Tensor (Scaler)
a = tf.constant(3)
print(a) # 'a' is a Rank 0 Tensor (0 dimensional array) of Int32

tf.Tensor(3, shape=(), dtype=int32)


In [14]:
# Rank 1 Tensor 
b = tf.constant([1 , 2 , 3 , 4])
print(b) # 'b' is a Rank 1 Tensor of Int32

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [15]:
# Rank 2 Tensor 
c = tf.constant([[1 , 2] , [3 , 4]])
print(c) # 'c' is a Rank 2 Tensor of Int32

# Similarly it's possible to create Tensor of any order 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### **Converting a Numpy array to Tensor**

In [16]:
array = np.array([1 , 2 , 3 , 4])
print(" Before " , array)
array = tf.convert_to_tensor(array)
print(" After " , array)

 Before  [1 2 3 4]
 After  tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


### **Arthematic operations on Tensor**

In [17]:
# Sample 2D tensor
tensor = tf.constant([[1 , 2] , [3 , 4]])

In [18]:
# Add 1 to all positions 
tensor = tf.add(tensor , 1)
print(" Added 1 " , tensor)

 Added 1  tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [19]:
# Sub 1 from all positions 
tensor = tf.subtract(tensor , 1)
print(" Subtracted 1 " , tensor)

 Subtracted 1  tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [20]:
# Div 2 on all positions 
tensor = tf.divide(tensor , 2)
print(" Divide by 2 " , tensor)

 Divide by 2  tf.Tensor(
[[0.5 1. ]
 [1.5 2. ]], shape=(2, 2), dtype=float64)


In [21]:
# Multiply with 2 
tensor = tf.multiply(tensor , 2)
print(" Multiply by 2 " , tensor)

# it's possible to perform arthematic operations over vectors 

 Multiply by 2  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float64)


### **Matrix Multiplication**

In [22]:
tensor = tf.constant([[1 , 2] , [3 , 4]])
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]])>

In [23]:
tf.multiply(tensor , tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]])>

In [3]:
tensor = tf.constant([[1,2], [5,10]], dtype=tf.float64)
tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1.,  2.],
       [ 5., 10.]])>

### **Applying activation functions:**
TensorFlow has all the Activation functions build it and ready to use.

In [4]:
# softmax
tf.nn.softmax(tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.26894142, 0.73105858],
       [0.00669285, 0.99330715]])>

In [5]:
# sigmoid
tf.nn.sigmoid(tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.73105858, 0.88079708],
       [0.99330715, 0.9999546 ]])>

In [7]:
# ReLU
tf.nn.relu(tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1.,  2.],
       [ 5., 10.]])>

In [8]:
# Leaky ReLU
tf.nn.leaky_relu(tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1.,  2.],
       [ 5., 10.]])>

### **Optimzers:**
TensorFlow also has all optimizers build (opmtimizers module) it and ready to use.

In [9]:
# Adam
optmizer = tf.keras.optimizers.Adam()
print(optmizer) # refers to optimizer class created

### **Basic Neural Network Structure:**

In [10]:
# Start the model with sequential object
model = tf.keras.models.Sequential()
# It's used to connect all the layers

# Next add a input object and specify the dimension you want to pass in
model.add(tf.keras.Input(shape=(10,)))
# the dimension should be the number of columns 
# in your dataset in case of predictive modeling

# Add the neurons of 1st layer using dense object
model.add(tf.keras.layers.Dense(32))

# 2nd layer using dense object
model.add(tf.keras.layers.Dense(16))

# print summary to understand the neural network flow created
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                352       
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
Total params: 880 (3.44 KB)
Trainable params: 880 (3.44 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


> If you keep adding more layers or increase the number of neurons in each layer, the trainable parameters increase as well.